name: movie_app_frontend
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  collection: ^1.18.0
  http_parser: ^4.0.2
  material_color_utilities: ^0.8.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
