name: movie_app_backend
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  alfred: ^1.1.1
  mongo_dart: ^0.10.3
  decimal: ^2.3.3  # 호환되는 버전으로 설정
  shelf: ^1.3.2
  http: ^1.0.0
  json_annotation: ^4.0.1
