import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:math';

class CriticRecommendations extends StatefulWidget {
  @override
  _CriticRecommendationsState createState() => _CriticRecommendationsState();
}

class _CriticRecommendationsState extends State<CriticRecommendations> {
  final String tmdbApiKey = 'd7e2c0c5a903a93afcfd18bd4e520a9a';
  final List<Map<String, String>> criticMovies = [
    {'title': '퓨리오사: 매드맥스 사가', 'rating': '4.5'},
    {'title': '악은 존재하지 않는다', 'rating': '4.5'},
    {'title': '추락의 해부', 'rating': '4.5'},
    {'title': '고모라', 'rating': '4.5'},
    {'title': '괴물', 'rating': '4.5'},
    {'title': '오펜하이머', 'rating': '4.5'},
    {'title': '애스터로이드 시티', 'rating': '4.5'},
    {'title': '서유기 2 - 선리기연', 'rating': '4.5'},
    {'title': '이니셰린의 밴시', 'rating': '4.5'},
    {'title': 'TAR 타르', 'rating': '4.5'},
    {'title': '서부 전선 이상 없다', 'rating': '4.5'},
    {'title': '메모리아', 'rating': '4.5'},
    {'title': '탑', 'rating': '4.5'},
    {'title': '사랑할 땐 누구나 최악이 된다', 'rating': '4.5'},
    {'title': '놉', 'rating': '4.5'},
    {'title': '애프터 양', 'rating': '4.5'},
    {'title': '매스', 'rating': '4.5'},
    {'title': '프랑스', 'rating': '4.5'},
    {'title': '맥베스의 비극', 'rating': '4.5'},
    {'title': '카우보이의 노래', 'rating': '4.5'},
    {'title': '휴머니티', 'rating': '4.5'},
    {'title': '프렌치 디스패치', 'rating': '4.5'},
    {'title': '파워 오브 도그', 'rating': '4.5'},
    {'title': '웬디와 루시', 'rating': '4.5'},
    {'title': '아네트', 'rating': '4.5'},
    {'title': '조용한 태양의 해', 'rating': '4.5'},
    {'title': '플랫폼', 'rating': '4.5'},
    {'title': '징후와 세기', 'rating': '4.5'},
    {'title': '열대병', 'rating': '4.5'},
    {'title': '해피 아워', 'rating': '4.5'},
    {'title': '피닉스', 'rating': '4.5'},
    {'title': '더 파더', 'rating': '4.5'},
    {'title': '소울', 'rating': '4.5'},
    {'title': '언컷 젬스', 'rating': '4.5'},
    {'title': '카메라를 멈추면 안 돼!', 'rating': '4.5'},
    {'title': '팀북투', 'rating': '4.5'},
    {'title': '지고이네르바이젠', 'rating': '4.5'},
    {'title': '45년 후', 'rating': '4.5'},
    {'title': '포드 V 페라리', 'rating': '4.5'},
    {'title': '조커', 'rating': '4.5'},
    {'title': '애드 아스트라', 'rating': '4.5'},
    {'title': '미드소마', 'rating': '4.5'},
    {'title': '기생충', 'rating': '4.5'},
    {'title': '퍼스트 리폼드', 'rating': '4.5'},
    {'title': '나그네는 길에서도 쉬지 않는다', 'rating': '4.5'},
    {'title': '짝코', 'rating': '4.5'},
    {'title': '아사코', 'rating': '4.5'},
    {'title': '콜드 워', 'rating': '4.5'},
    {'title': '고스트 스토리', 'rating': '4.5'},
    {'title': '바르다가 사랑한 얼굴들', 'rating': '4.5'},
    {'title': '어느 가족', 'rating': '4.5'},
    {'title': '천국보다 낯선', 'rating': '4.5'},
    {'title': '유전', 'rating': '4.5'},
    {'title': '이마 베프', 'rating': '4.5'},
    {'title': '스위티', 'rating': '4.5'},
    {'title': '생선 쿠스쿠스', 'rating': '4.5'},
    {'title': '더 포스트', 'rating': '4.5'},
    {'title': '셰이프 오브 워터: 사랑의 모양', 'rating': '4.5'},
    {'title': '패터슨', 'rating': '4.5'},
    {'title': '오고 가며', 'rating': '4.5'},
    {'title': '철남 1', 'rating': '4.5'},
    {'title': '당신과 함께한 순간들', 'rating': '4.5'},
    {'title': '어 퍼펙트 데이', 'rating': '4.5'},
    {'title': '엘르', 'rating': '4.5'},
    {'title': '에이리언 2', 'rating': '4.5'},
    {'title': '밤의 해변에서 혼자', 'rating': '4.5'},
    {'title': '토니 에드만', 'rating': '4.5'},
    {'title': '문라이트', 'rating': '4.5'},
    {'title': '로스트 인 더스트', 'rating': '4.5'},
    {'title': '돼지가 우물에 빠진 날', 'rating': '4.5'},
    {'title': '다가오는 것들', 'rating': '4.5'},
    {'title': '클라커즈', 'rating': '4.5'},
    {'title': '달콤한 후세', 'rating': '4.5'},
    {'title': '녹색 광선', 'rating': '4.5'},
    {'title': '이블 데드 2', 'rating': '4.5'},
    {'title': '블레이드 러너', 'rating': '4.5'},
    {'title': '스카페이스', 'rating': '4.5'},
    {'title': '먼 목소리, 조용한 삶', 'rating': '4.5'},
    {'title': '나의 성생활: 나는 어떻게 싸웠는가', 'rating': '4.5'},
    {'title': '욜', 'rating': '4.5'},
    {'title': '란', 'rating': '4.5'},
    {'title': '아이언 자이언트', 'rating': '4.5'},
    {'title': '프로메제', 'rating': '4.5'},
    {'title': '안녕, 용문객잔', 'rating': '4.5'},
    {'title': '하류', 'rating': '4.5'},
    {'title': '맨하탄', 'rating': '4.5'},
    {'title': '조지아', 'rating': '4.5'},
    {'title': '헤비', 'rating': '4.5'},
    {'title': '시테라 섬으로의 여행', 'rating': '4.5'},
    {'title': '월레스와 그로밋 - 걸작선', 'rating': '4.5'},
    {'title': '언더그라운드', 'rating': '4.5'},
    {'title': '집시의 시간', 'rating': '4.5'},
    {'title': '똑바로 살아라', 'rating': '4.5'},
    {'title': '더스트', 'rating': '4.5'},
    {'title': '숏컷', 'rating': '4.5'},
    {'title': '태양', 'rating': '4.5'},
    {'title': '로스트 하이웨이', 'rating': '4.5'},
    {'title': '흑사회 2', 'rating': '4.5'},
    {'title': '흑사회', 'rating': '4.5'},
    {'title': '프로젝트 A', 'rating': '4.5'},
    {'title': '용서받지 못한 자', 'rating': '4.5'},
    {'title': '살인에 관한 짧은 필름', 'rating': '4.5'},
    {'title': '배트맨 2', 'rating': '4.5'},
    {'title': '나쁜 피', 'rating': '4.5'},
    {'title': '올리브 나무 사이로', 'rating': '4.5'},
    {'title': '내 친구의 집은 어디인가', 'rating': '4.5'},
    {'title': '저수지의 개들', 'rating': '4.5'},
    {'title': '만다라', 'rating': '4.5'},
    {'title': '티켓', 'rating': '4.5'},
    {'title': '해상화', 'rating': '4.5'},
    {'title': '희몽인생', 'rating': '4.5'},
    {'title': '바람계곡의 나우시카', 'rating': '4.5'},
    {'title': '특근', 'rating': '4.5'},
    {'title': '아이들의 왕', 'rating': '4.5'},
    {'title': '스토리텔링', 'rating': '4.5'},
    {'title': '해피니스', 'rating': '4.5'},
    {'title': '바톤 핑크', 'rating': '4.5'},
    {'title': '위대한 레보스키', 'rating': '4.5'},
    {'title': '증오', 'rating': '4.5'},
    {'title': '철서구 2부 - 폐허', 'rating': '4.5'},
    {'title': '철서구 3부 - 철로', 'rating': '4.5'},
    {'title': '철서구 1부 - 녹', 'rating': '4.5'},
    {'title': '헨리: 연쇄살인범의 초상', 'rating': '4.5'},
    {'title': '우리들', 'rating': '4.5'},
    {'title': '아노말리사', 'rating': '4.5'},
    {'title': '스포트라이트', 'rating': '4.5'},
    {'title': '빅쇼트', 'rating': '4.5'},
    {'title': '시카리오: 암살자의 도시', 'rating': '4.5'},
    {'title': '지금은맞고그때는틀리다', 'rating': '4.5'},
    {'title': '이민자', 'rating': '4.5'},
    {'title': '투 러버스', 'rating': '4.5'},
    {'title': '헝거', 'rating': '4.5'},
    {'title': '체리향기', 'rating': '4.5'},
    {'title': '그리고 삶은 계속된다', 'rating': '4.5'},
    {'title': 'LA 컨피덴셜', 'rating': '4.5'},
    {'title': '브라질', 'rating': '4.5'},
    {'title': '베라 드레이크', 'rating': '4.5'},
    {'title': '소년 소녀를 만나다', 'rating': '4.5'},
    {'title': '동사서독 리덕스', 'rating': '4.5'},
    {'title': '베크마이스터 하모니즈', 'rating': '4.5'},
    {'title': '젤리그', 'rating': '4.5'},
    {'title': '러시아 방주', 'rating': '4.5'},
    {'title': '아름다운 직업', 'rating': '4.5'},
    {'title': '카게무샤', 'rating': '4.5'},
    {'title': '미지와의 조우', 'rating': '4.5'},
    {'title': '우주전쟁', 'rating': '4.5'},
    {'title': '인디아나 존스: 마궁의 사원', 'rating': '4.5'},
    {'title': '레이더스', 'rating': '4.5'},
    {'title': '기쁜 우리 젊은 날', 'rating': '4.5'},
    {'title': '로저와 나', 'rating': '4.5'},
    {'title': '사탄의 태양 아래', 'rating': '4.5'},
    {'title': '위선의 태양', 'rating': '4.5'},
    {'title': '중앙역', 'rating': '4.5'},
    {'title': '호수의 이방인', 'rating': '4.5'},
    {'title': '라스트 왈츠', 'rating': '4.5'},
    {'title': '마음', 'rating': '4.5'},
    {'title': '칠드런 오브 맨', 'rating': '4.5'},
    {'title': '빅 나이트', 'rating': '4.5'},
    {'title': '부기 나이트', 'rating': '4.5'},
    {'title': '짙은 선홍색', 'rating': '4.5'},
    {'title': '후프 드림스', 'rating': '4.5'},
    {'title': '레즈', 'rating': '4.5'},
    {'title': '리턴', 'rating': '4.5'},
    {'title': '푸줏간 소년', 'rating': '4.5'},
    {'title': '스모킹/노스모킹', 'rating': '4.5'},
    {'title': '카지노', 'rating': '4.5'},
    {'title': '레이닝 스톤', 'rating': '4.5'},
    {'title': '허공에의 질주', 'rating': '4.5'},
    {'title': '롤라 런', 'rating': '4.5'},
    {'title': '장군', 'rating': '4.5'},
    {'title': '재키 브라운', 'rating': '4.5'},
    {'title': '대지', 'rating': '4.5'},
    {'title': '사랑의 블랙홀', 'rating': '4.5'},
    {'title': '우묵배미의 사랑', 'rating': '4.5'},
    {'title': '닉슨', 'rating': '4.5'},
    {'title': '키리시마가 동아리활동 그만둔대', 'rating': '4.5'},
    {'title': '한여름의 판타지아', 'rating': '4.5'},
    {'title': '매드맥스: 분노의 도로', 'rating': '4.5'},
    {'title': '쥬드', 'rating': '4.5'},
    {'title': '내 어머니의 모든 것', 'rating': '4.5'},
    {'title': '춘향뎐', 'rating': '4.5'},
    {'title': '라이언 일병 구하기', 'rating': '4.5'},
    {'title': '죽거나 혹은 나쁘거나', 'rating': '4.5'},
    {'title': '펄프 픽션', 'rating': '4.5'},
    {'title': '키즈 리턴', 'rating': '4.5'},
    {'title': '아이즈 와이드 셧', 'rating': '4.5'},
    {'title': '8월의 크리스마스', 'rating': '4.5'},
    {'title': '시네마 천국', 'rating': '4.5'},
    {'title': '인어공주', 'rating': '4.5'},
    {'title': '토이 스토리', 'rating': '4.5'},
    {'title': '타이타닉', 'rating': '4.5'},
    {'title': '포르노그래픽 어페어', 'rating': '4.5'},
    {'title': '언브레이커블', 'rating': '4.5'},
    {'title': '빌리 엘리어트', 'rating': '4.5'},
    {'title': '성냥공장 소녀', 'rating': '4.5'},
    {'title': '타인의 취향', 'rating': '4.5'},
    {'title': '메멘토', 'rating': '4.5'},
    {'title': '귀신이 온다', 'rating': '4.5'},
    {'title': '이다', 'rating': '4.5'},
    {'title': '내일을 위한 시간', 'rating': '4.5'},
    {'title': '파이', 'rating': '4.5'},
    {'title': '아멜리에', 'rating': '4.5'},
    {'title': '공각기동대', 'rating': '4.5'},
    {'title': '펀치 드렁크 러브', 'rating': '4.5'},
    {'title': '해피 투게더 리마스터링', 'rating': '4.5'},
    {'title': '니모를 찾아서', 'rating': '4.5'},
    {'title': '시카고', 'rating': '4.5'},
    {'title': '엑스맨 2', 'rating': '4.5'},
    {'title': '터미네이터 2', 'rating': '4.5'},
    {'title': '반지의 제왕 : 반지 원정대', 'rating': '4.5'},
    {'title': '과거가 없는 남자', 'rating': '4.5'},
    {'title': '아무도 모른다', 'rating': '4.5'},
    {'title': '극장전', 'rating': '4.5'},
    {'title': '그때 그사람들', 'rating': '4.5'},
    {'title': '달콤한 인생', 'rating': '4.5'},
    {'title': '스타워즈 에피소드 5: 제국의 역습', 'rating': '4.5'},
    {'title': '영원과 하루', 'rating': '4.5'},
    {'title': '취한 말들을 위한 시간', 'rating': '4.5'},
    {'title': '조제, 호랑이 그리고 물고기들', 'rating': '4.5'},
    {'title': '스파이더맨 2', 'rating': '4.5'},
    {'title': '친절한 금자씨', 'rating': '4.5'},
    {'title': '영웅본색', 'rating': '4.5'},
    {'title': '지구를 지켜라!', 'rating': '4.5'},
    {'title': '러브레터', 'rating': '4.5'},
    {'title': '아마데우스', 'rating': '4.5'},
    {'title': '킬러들의 도시', 'rating': '4.5'},
    {'title': '엑스맨: 데이즈 오브 퓨처 패스트', 'rating': '4.5'},
    {'title': '그녀', 'rating': '4.5'},
    {'title': '이오지마에서 온 편지', 'rating': '4.5'},
    {'title': '가위손', 'rating': '4.5'},
    {'title': '록키 호러 픽쳐 쇼', 'rating': '4.5'},
    {'title': '샤이닝', 'rating': '4.5'},
    {'title': '블루 발렌타인', 'rating': '4.5'},
    {'title': '이티', 'rating': '4.5'},
    {'title': '행복', 'rating': '4.5'},
    {'title': '타짜', 'rating': '4.5'},
    {'title': '캐빈 인 더 우즈', 'rating': '4.5'},
    {'title': '시저는 죽어야 한다', 'rating': '4.5'},
    {'title': '색, 계', 'rating': '4.5'},
    {'title': '사랑을 카피하다', 'rating': '4.5'},
    {'title': '미스틱 리버', 'rating': '4.5'},
    {'title': '미스트', 'rating': '4.5'},
    {'title': '만추', 'rating': '4.5'},
    {'title': '공기인형', 'rating': '4.5'},
    {'title': '허트 로커', 'rating': '4.5'},
    {'title': '황해', 'rating': '4.5'},
    {'title': '파수꾼', 'rating': '4.5'},
    {'title': '킹콩', 'rating': '4.5'},
    {'title': '토니 타키타니', 'rating': '4.5'},
    {'title': '토이 스토리 3', 'rating': '4.5'},
    {'title': '케빈에 대하여', 'rating': '4.5'},
    {'title': '파우스트', 'rating': '4.5'},
    {'title': '테이크 쉘터', 'rating': '4.5'},
    {'title': '24 시티', 'rating': '4.5'},
    {'title': '인어공주', 'rating': '4.5'},
    {'title': '자토이치', 'rating': '4.5'},
    {'title': '인 디 에어', 'rating': '4.5'},
    {'title': '인랜드 엠파이어', 'rating': '4.5'},
    {'title': '일루셔니스트', 'rating': '4.5'},
    {'title': '진짜로 일어날지도 몰라 기적', 'rating': '4.5'},
    {'title': '지슬 - 끝나지 않은 세월2', 'rating': '4.5'},
    {'title': '유레루', 'rating': '4.5'},
    {'title': '500일의 썸머', 'rating': '4.5'},
    {'title': '월-E', 'rating': '4.5'},
    {'title': '엉클 분미', 'rating': '4.5'},
    {'title': 'M', 'rating': '4.5'},
    {'title': '예언자', 'rating': '4.5'},
    {'title': '시', 'rating': '4.5'},
    {'title': '슈렉 2', 'rating': '4.5'},
    {'title': '시티 오브 갓', 'rating': '4.5'},
    {'title': '시간을 달리는 소녀', 'rating': '4.5'},
    {'title': '아임 낫 데어', 'rating': '4.5'},
    {'title': '아바타', 'rating': '4.5'},
    {'title': '악마가 너의 죽음을 알기 전에', 'rating': '4.5'},
    {'title': '아무르', 'rating': '4.5'},
    {'title': '씨민과 나데르의 별거', 'rating': '4.5'},
    {'title': '브로크백 마운틴', 'rating': '4.5'},
    {'title': '소셜 네트워크', 'rating': '4.5'},
    {'title': '사랑니', 'rating': '4.5'},
    {'title': '블랙 스완', 'rating': '4.5'},
    {'title': '송환', 'rating': '4.5'},
    {'title': '북촌방향', 'rating': '4.5'},
    {'title': '서칭 포 슈가맨', 'rating': '4.5'},
    {'title': '본 슈프리머시', 'rating': '4.5'},
    {'title': '바시르와 왈츠를', 'rating': '4.5'},
    {'title': '미션 임파서블 3', 'rating': '4.5'},
    {'title': '범죄와의 전쟁 : 나쁜놈들 전성시대', 'rating': '4.5'},
    {'title': '비포 미드나잇', 'rating': '4.5'},
    {'title': '블루 재스민', 'rating': '4.5'},
    {'title': '렛 미 인', 'rating': '4.5'},
    {'title': '마을에 부는 산들바람', 'rating': '4.5'},
    {'title': '라이프 오브 파이', 'rating': '4.5'},
    {'title': '머니볼', 'rating': '4.5'},
    {'title': '셰임', 'rating': '4.5'},
    {'title': '다우트', 'rating': '4.5'},
    {'title': '괴물', 'rating': '4.5'},
    {'title': '달은 어디에 떠 있는가', 'rating': '4.5'},
    {'title': '그랜 토리노', 'rating': '4.5'},
    {'title': '더 폴: 오디어스와 환상의 문', 'rating': '4.5'},
    {'title': '007 스카이폴', 'rating': '4.5'},
    {'title': '가족의 탄생', 'rating': '4.5'},
    {'title': '본 얼티메이텀', 'rating': '4.5'},
    {'title': '장고: 분노의 추적자', 'rating': '4.5'},
    {'title': '올드보이', 'rating': '4.5'},
    {'title': '혹성탈출: 진화의 시작', 'rating': '4.5'},
    {'title': '업', 'rating': '5'},
    {'title': '다크 나이트', 'rating': '5'},
    {'title': '킬 빌', 'rating': '5'},
    {'title': '반지의 제왕: 왕의 귀환', 'rating': '5'},
    {'title': '데어 윌 비 블러드', 'rating': '5'},
    {'title': '마더', 'rating': '5'},
    {'title': '레볼루셔너리 로드', 'rating': '5'},
    {'title': '멜랑콜리아', 'rating': '5'},
    {'title': '조디악', 'rating': '5'},
    {'title': '킬 빌 2', 'rating': '5'},
    {'title': '바스터즈: 거친 녀석들', 'rating': '5'},
    {'title': '늑대아이', 'rating': '5'},
    {'title': '마스터', 'rating': '5'},
    {'title': '걸어도 걸어도', 'rating': '5'},
    {'title': '박쥐', 'rating': '5'},
    {'title': '노인을 위한 나라는 없다', 'rating': '5'},
    {'title': '빅 피쉬', 'rating': '5'},
    {'title': '세상의 모든 계절', 'rating': '5'},
    {'title': '밀양', 'rating': '5'},
    {'title': '아들', 'rating': '5'},
    {'title': '토리노의 말', 'rating': '5'},
    {'title': '자전거 탄 소년', 'rating': '5'},
    {'title': '시리어스 맨', 'rating': '5'},
    {'title': '아이 엠 러브', 'rating': '5'},
    {'title': '안티크라이스트', 'rating': '5'},
    {'title': '이터널 선샤인', 'rating': '5'},
    {'title': '스틸 라이프', 'rating': '5'},
    {'title': '원스', 'rating': '5'},
    {'title': '옥희의 영화', 'rating': '5'},
    {'title': '당신은 아직 아무것도 보지 못했다', 'rating': '5'},
    {'title': '홀리 모터스', 'rating': '5'},
    {'title': '그래비티', 'rating': '5'},
    {'title': '인사이드 르윈', 'rating': '5'},
    {'title': '판의 미로 - 오필리아와 세 개의 열쇠', 'rating': '5'},
    {'title': '하얀 리본', 'rating': '5'},
    {'title': '해변의 여인', 'rating': '5'},
    {'title': '우리도 사랑일까', 'rating': '5'},
    {'title': '비포 선셋', 'rating': '5'},
    {'title': '그랜드 부다페스트 호텔', 'rating': '5'},
    {'title': '파이트 클럽', 'rating': '5'},
    {'title': '에이리언', 'rating': '5'},
    {'title': '엘리펀트', 'rating': '5'},
    {'title': '릴리 슈슈의 모든 것', 'rating': '5'},
    {'title': '살인의 추억', 'rating': '5'},
    {'title': '반지의 제왕: 두 개의 탑', 'rating': '5'},
    {'title': '매트릭스', 'rating': '5'},
    {'title': '피아니스트', 'rating': '5'},
    {'title': '센과 치히로의 행방불명', 'rating': '5'},
    {'title': '디 아워스', 'rating': '5'},
    {'title': '하나 그리고 둘', 'rating': '5'},
    {'title': '레퀴엠', 'rating': '5'},
    {'title': '복수는 나의 것', 'rating': '5'},
    {'title': '복수는 나의 것', 'rating': '5'},
    {'title': '와이키키 브라더스', 'rating': '5'},
    {'title': '원더풀 라이프', 'rating': '5'},
    {'title': '보이후드', 'rating': '5'},
    {'title': '액트 오브 킬링', 'rating': '5'},
    {'title': '언더 더 스킨', 'rating': '5'},
    {'title': '폭스캐처', 'rating': '5'},
    {'title': '위플래쉬', 'rating': '5'},
    {'title': '봄날은 간다', 'rating': '5'},
    {'title': '멀홀랜드 드라이브', 'rating': '5'},
    {'title': '에이 아이', 'rating': '5'},
    {'title': '소름', 'rating': '5'},
    {'title': '양들의 침묵', 'rating': '5'},
    {'title': '인정사정 볼 것 없다', 'rating': '5'},
    {'title': '박하사탕', 'rating': '5'},
    {'title': '백치들', 'rating': '5'},
    {'title': '매그놀리아', 'rating': '5'},
    {'title': '벨벳 골드마인', 'rating': '5'},
    {'title': '소나티네', 'rating': '5'},
    {'title': '원스 어폰 어 타임 인 아메리카', 'rating': '5'},
    {'title': '사랑에 관한 짧은 필름', 'rating': '5'},
    {'title': '나라야마 부시코', 'rating': '5'},
    {'title': '아이스 스톰', 'rating': '5'},
    {'title': '배드 캅', 'rating': '5'},
    {'title': '안개 속의 풍경', 'rating': '5'},
    {'title': '이웃집 토토로', 'rating': '5'},
    {'title': '크리스마스에 눈이 올까요?', 'rating': '5'},
    {'title': '스톱 메이킹 센스', 'rating': '5'},
    {'title': '사탄탱고', 'rating': '5'},
    {'title': '아비정전', 'rating': '5'},
    {'title': '화양연화 리마스터링', 'rating': '5'},
    {'title': '고령가 소년 살인사건', 'rating': '5'},
    {'title': '강원도의 힘', 'rating': '5'},
    {'title': '첫사랑', 'rating': '5'},
    {'title': '캐롤', 'rating': '5'},
    {'title': '사울의 아들', 'rating': '5'},
    {'title': '곡성(哭聲)', 'rating': '5'},
    {'title': '광기가 우리를 갈라놓을 때까지', 'rating': '5'},
    {'title': '밀러스 크로싱', 'rating': '5'},
    {'title': '좋은 친구들', 'rating': '5'},
    {'title': '분노의 주먹', 'rating': '5'},
    {'title': '비정성시', 'rating': '5'},
    {'title': '남국재견', 'rating': '5'},
    {'title': '길소뜸', 'rating': '5'},
    {'title': '텐', 'rating': '5'},
    {'title': '클로즈 업', 'rating': '5'},
    {'title': '괴물', 'rating': '5'},
    {'title': '어머니와 아들', 'rating': '5'},
    {'title': '로제타', 'rating': '5'},
    {'title': '쇼아', 'rating': '5'},
    {'title': '자연의 아이들', 'rating': '5'},
    {'title': '버림받은 천사들', 'rating': '5'},
    {'title': '큐어', 'rating': '5'},
    {'title': '밀리언 달러 베이비', 'rating': '5'},
    {'title': '라라랜드', 'rating': '5'},
    {'title': '컨택트', 'rating': '5'},
    {'title': '퍼스널 쇼퍼', 'rating': '5'},
    {'title': '덩케르크', 'rating': '5'},
    {'title': '유레카', 'rating': '5'},
    {'title': '팬텀 스레드', 'rating': '5'},
    {'title': '버닝', 'rating': '5'},
    {'title': '킬링 디어', 'rating': '5'},
    {'title': '인 디 아일', 'rating': '5'},
    {'title': '로마', 'rating': '5'},
    {'title': '남쪽', 'rating': '5'},
    {'title': '최후의 증인', 'rating': '5'},
    {'title': '바보선언', 'rating': '5'},
    {'title': '달마가 동쪽으로 간 까닭은?', 'rating': '5'},
    {'title': '희생', 'rating': '5'},
    {'title': '노스탤지아', 'rating': '5'},
    {'title': '지구 최후의 밤', 'rating': '5'},
    {'title': '경계선', 'rating': '5'},
    {'title': '아이리시맨', 'rating': '5'},
    {'title': '카메라를 든 사람', 'rating': '5'},
    {'title': '리버풀', 'rating': '5'},
    {'title': '타오르는 여인의 초상', 'rating': '5'},
    {'title': '이제 그만 끝낼까 해', 'rating': '5'},
    {'title': '레 미제라블', 'rating': '5'},
    {'title': '그린 나이트', 'rating': '5'},
    {'title': '자마', 'rating': '5'},
    {'title': '퍼스트 카우', 'rating': '5'},
    {'title': '드라이브 마이 카', 'rating': '5'},
    {'title': '헤어질 결심', 'rating': '5'},
    {'title': '라이트하우스', 'rating': '5'},
    {'title': '에브리씽 에브리웨어 올 앳 원스', 'rating': '5'},
    {'title': '애프터썬', 'rating': '5'},
    {'title': '파벨만스', 'rating': '5'},
    {'title': '노 베어스', 'rating': '5'},
    {'title': '존 오브 인터레스트', 'rating': '5'},
  ];

  Future<List<Map<String, String>>> fetchMoviePosters(
      List<Map<String, String>> selectedMovies) async {
    List<Map<String, String>> moviesWithPosters = [];

    for (var movie in selectedMovies) {
      final response = await http.get(Uri.parse(
          'https://api.themoviedb.org/3/search/movie?api_key=$tmdbApiKey&query=${movie['title']}&language=ko-KR&region=KR'));
      if (response.statusCode == 200) {
        final results = json.decode(response.body)['results'];
        if (results.isNotEmpty) {
          movie['posterUrl'] =
              'https://image.tmdb.org/t/p/w500${results[0]['poster_path']}';
        } else {
          movie['posterUrl'] = 'https://via.placeholder.com/150';
        }
      } else {
        movie['posterUrl'] = 'https://via.placeholder.com/150';
      }
      moviesWithPosters.add(movie);
    }
    return moviesWithPosters;
  }

  Future<List<Map<String, String>>> getRandomMovies() async {
    final random = Random();
    final selectedMovies = List.generate(
        5, (_) => criticMovies[random.nextInt(criticMovies.length)]);
    return await fetchMoviePosters(selectedMovies);
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<List<Map<String, String>>>(
      future: getRandomMovies(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        } else if (snapshot.hasError) {
          print('Error: ${snapshot.error}');
          return Center(child: Text('Error: ${snapshot.error}'));
        } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
          return Center(child: Text('No data found'));
        } else {
          final movies = snapshot.data!;
          return Container(
            margin: EdgeInsets.symmetric(vertical: 20.0),
            height: 250.0,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: movies.length,
              itemBuilder: (context, index) {
                final movie = movies[index];
                final posterPath =
                    movie['posterUrl'] ?? 'https://via.placeholder.com/150';

                return Card(
                  margin: EdgeInsets.all(8.0),
                  child: Container(
                    width: 160.0,
                    child: Column(
                      children: [
                        Image.network(posterPath,
                            height: 150, fit: BoxFit.cover),
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Text(
                            movie['title']!,
                            overflow: TextOverflow.ellipsis,
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          );
        }
      },
    );
  }
}
